Repository EJComp-Unesp/Dvora-Backend, pull requests merged in 2020-07, with the labels that each got.

#56 GET dos plantões abertos no dia atual de consulta por EJ
  src/controllers/DutyController.js
  src/routes.js
Labels: enhancement

#60 Mudança da recuperação do id do membro por params
  src/controllers/FeedbackController.js
  src/routes.js
Labels: adjustment

#62 Fix: Pedindo o jeId pelo params
  src/controllers/FeedbackController.js
  src/routes.js
Labels: adjustment, bug

#63 Arrumado verificação de feedback quando nulo
  src/controllers/FeedbackController.js
Labels: bug

#67 Ajuste no update de Ej
  src/controllers/JeController.js
Labels: adjustment

#41 Hotfix/token
  src/config/auth.json
  src/controllers/BoardController.js
  src/controllers/DutyController.js
  src/controllers/FeedbackController.js
  src/controllers/JeController.js
  src/controllers/LoginController.js
  src/controllers/MemberController.js
  src/middlewares/auth.js
  src/middlewares/authJe.js
  src/routes.js
Labels: adjustment
